apiVersion: v1
kind: Pod
spec:
  containers:
    - name: main
      image: linuxserver/openssh-server:9.7_p1-r4-ls169
      env:
        - name: SUDO_ACCESS
          value: "true"
        - name: USER_NAME
          value: "ssh"
        - name: LOG_STDOUT
          value: "true"
        - name: PUID
          value: "0"
      readinessProbe:
        tcpSocket:
          port: 2222
